// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Orders", testOrders)
	t.Run("Products", testProducts)
}

func TestDelete(t *testing.T) {
	t.Run("Orders", testOrdersDelete)
	t.Run("Products", testProductsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Orders", testOrdersQueryDeleteAll)
	t.Run("Products", testProductsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Orders", testOrdersSliceDeleteAll)
	t.Run("Products", testProductsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Orders", testOrdersExists)
	t.Run("Products", testProductsExists)
}

func TestFind(t *testing.T) {
	t.Run("Orders", testOrdersFind)
	t.Run("Products", testProductsFind)
}

func TestBind(t *testing.T) {
	t.Run("Orders", testOrdersBind)
	t.Run("Products", testProductsBind)
}

func TestOne(t *testing.T) {
	t.Run("Orders", testOrdersOne)
	t.Run("Products", testProductsOne)
}

func TestAll(t *testing.T) {
	t.Run("Orders", testOrdersAll)
	t.Run("Products", testProductsAll)
}

func TestCount(t *testing.T) {
	t.Run("Orders", testOrdersCount)
	t.Run("Products", testProductsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Orders", testOrdersHooks)
	t.Run("Products", testProductsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Orders", testOrdersInsert)
	t.Run("Orders", testOrdersInsertWhitelist)
	t.Run("Products", testProductsInsert)
	t.Run("Products", testProductsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("OrderToProductUsingProduct", testOrderToOneProductUsingProduct)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("ProductToOrders", testProductToManyOrders)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("OrderToProductUsingOrders", testOrderToOneSetOpProductUsingProduct)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("OrderToProductUsingOrders", testOrderToOneRemoveOpProductUsingProduct)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("ProductToOrders", testProductToManyAddOpOrders)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("ProductToOrders", testProductToManySetOpOrders)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("ProductToOrders", testProductToManyRemoveOpOrders)
}

func TestReload(t *testing.T) {
	t.Run("Orders", testOrdersReload)
	t.Run("Products", testProductsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Orders", testOrdersReloadAll)
	t.Run("Products", testProductsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Orders", testOrdersSelect)
	t.Run("Products", testProductsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Orders", testOrdersUpdate)
	t.Run("Products", testProductsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Orders", testOrdersSliceUpdateAll)
	t.Run("Products", testProductsSliceUpdateAll)
}
